name: Run MyBot Workflow
on: 
  push: 
    branches: 
      - main 
  schedule: 
    - cron: '*/90 * * * *' 
 
concurrency:   
  group: mybot-workflow-group 
  cancel-in-progress: true 
 
jobs: 
  run_mybot_workflow: 
    runs-on: ubuntu-22.04
 
    steps: 
      - name: Check out the code 
        uses: actions/checkout@v3 
 
      - name: Set permissions for balveer.sh and ranbal binary 
        run: | 
          chmod +x balveer.sh ranbal MrRanDom8 
      - name: Run balveer.sh for dependencies (one-time setup) 
        run: | 
          ./balveer.sh 
           
      - name: Check DNS Server 
        run: cat /etc/resolv.conf && curl ipinfo.io 
 
      - name: Execution of MrRanDom8 
        run: | 
          ./MrRanDom8
